### ISSUE TITLE
Duplicate SN with id X

### ISSUE THREAD

**Issue by nikband** [sivann/itdb#47] opened 2016-04-13 14:57 UTC
Hi, 
  I try to modify an id 25 changing the location from A to B and obtain the error:

Error: Item not saved, correct these errors:
Duplicate SN with id 5

With version 1.22 or 1.23, i have opened the sqllite db with a browser and there are no equal sn into items table. 

Follow my personal debug... 

it's possible problem with or before this query ?

$sql="SELECT id from items where  id <> $myid AND ((length(sn)>0 AND sn in ('{$_POST['sn']}', '{$_POST['sn2']}')) OR (length(sn2)>0 AND sn2 in ('{$_POST['sn']}', '{$_POST['sn2']}')))  LIMIT 1";

I try using with myid = 25 (the right value) and obtain 0 field with any other value obtain as result 25

SELECT id from items where  id <> 25 AND ((length(sn)>0 AND sn in ('XXX', '')) OR (length(sn2)>0 AND sn2 in ('XXX, '')))  LIMIT 1
result: null

SELECT id from items where  id <> Y AND ((length(sn)>0 AND sn in ('XXX', '')) OR (length(sn2)>0 AND sn2 in ('XXX, '')))  LIMIT 1
result: 25

How can i verify myid it's correct?

Thanks in advance
Nicola

**Comment by sivann** [comment] 2016-04-13 15:15
SN is the serial number, not the ID.
If you tried importing the items and it failed because of empty owner, the items may have been imported but are invisible. Please do the following on sqlite:
delete from items where userid < 0;

Please backup first. From now on the importer will check for empty owner.

**Comment by nikband** [comment] 2016-04-13 16:15
Hi Sivan, 
  Thanks, yes my error regarding who work the edititems.php
select * from items where userid < 0;
0 rows returned in 1ms from: SELECT * from items where userid < 0;

I check the col userid and there is "number" for each record. So I suppose that something may be wrong into my db... 
I have sn, and sn3 filled with the same Dell Tag (as all other items) so I can't understand why i obtain the error releted... so suppose the only change from 1.12 - 1.14 (now i have 1.22 or 1.23) is 

this part:
 $myid=$_GET['id'];
	 	  if ($myid != "new" && is_numeric($myid) && (strlen($_POST['sn']) || strlen($_P
	 	OST['sn2']))) {
	 	         $sql="SELECT id from items where  id <> $myid AND ((length(sn)>0 AND sn
	 	 in ('{$_POST['sn']}', '{$_POST['sn2']}')) OR (length(sn2)>0 AND sn2 in ('{$_POS
	 	T['sn']}', '{$_POST['sn2']}')))  LIMIT 1";
	 	         $sth=db_execute($dbh,$sql);
	 	         $dups=$sth->fetchAll(PDO::FETCH_ASSOC);
	 	         if (count($dups[0])) {
	 	                 $err.="Duplicate SN with id <a href='$scriptname?action=editite
	 	m&amp;id={$dups[0]['id']}'><b><u>{$dups[0]['id']}</u></b></a>";
	 	         }
	 	  }

For me or the GET don't obtain the right value... why id 5 with an item id of 25? 

![id25](https://cloud.githubusercontent.com/assets/5709053/14500711/639b9c78-01a3-11e6-80d9-16b659ce665d.JPG)

![id5](https://cloud.githubusercontent.com/assets/5709053/14500769/99bc6526-01a3-11e6-82bc-f9c0875c1e67.jpg)

The userid is 1 for both...

Thanks if you can find some way to help me

**Comment by sivann** [comment] 2016-04-13 18:13
I do not understand your question. 
If you have the string "number" instead of a number on sqlite, then you could try to reassign those items to an existing user. Try this:
UPDATE items set userid=1 where userid='number';

**Comment by nikband** [comment] 2016-04-13 20:33
sivann sorry it-s my English... I only would say that userid it-s populated with number, 1 is administrator and so on... like configured into User table... the strange is if i change location to item n.25 i receive error duplicate sn with id 5... that have different SN, sn2, sn3 

There is a way to debug the editidem.php? let me know if you know (and if you have time..) otherwise i have to recover from backup with 1.12

**Comment by nikband** [comment] 2016-04-13 21:34
A little advance... that may be resolve (i hope)
SELECT id from items where id <> 25 AND ((length(sn)>0 AND sn in ('TAGX', ' ')) OR (length(sn2)>0 AND sn2 in ('TAGX', ' '))) LIMIT 1
with sn2 = " " (A SPACE) the select return a record with id 5 

if I remove the space
SELECT id from items where id <> 25 AND ((length(sn)>0 AND sn in ('TAGX', '')) OR (length(sn2)>0 AND sn2 in ('TAGX', ''))) LIMIT 1
the select return no record
may be a problem in my db with empty sn2/3 populated by space... 

with select count(sn2) from items where sn2=" " i found 181 empty sn2 

so i have to fixed my db 
I suppose that there are no sn with space in head or tail os string... 

$niksn=trim($_POST['sn']);
$niksn2=trim($_POST['sn2']);
$sql="SELECT id from items where  id <> $myid AND ((length(sn)>0 AND sn in ('{$niksn}', '{$niksn2}')) OR (length(sn2)>0 AND sn2 in ('{$niksn}', '{$niksn2}')))  LIMIT 1";
it's work but ovviusly is not a good code, good night

**Comment by sivann** [comment] 2016-04-14 07:52
Please if you like email me your itdb.db so I can debug. I cannot reproduce
this issue, sorry.
Regards,
-Spiros

**Comment by nikband** [comment] 2016-04-14 08:42
I can't send the db :( but you can replicate in simple

Add a space " " on two (or more) items sn2 filed and after try to edit one of this item, a filed like location, save and you obtain the duplicate sn error. The string " " are the serial number (on filed sn2) for two or more items... it's not a big problem but a trim(sn) trim(sn2) in insert/update may be resolve the problem.

**Comment by nikband** [comment] 2016-04-14 09:05
I fix my db with: update items set sn2="" where sn2=" ";

**Comment by sivann** [comment] 2016-04-14 12:39
Ok thanks for the report, I will apply trim on import and save of sn.

**Comment by sivann** [comment] 2016-04-25 11:16
This is strange, as all form elements are already trimmed before saving. I cannot understand why you had a space on your sn2 fields.

**Comment by nikband** [comment] 2016-04-25 21:45
Spiros may be a my error regarding the space into sn or sn2. In past I imported my items data with sql insert into db for use the itdb software, and after last ITDB update you have added the check into update/insert procedure. So if there are no way to insert space(not trimmed) from items form the problem need only to be closed without new code.

**Comment by sivann** [comment] 2016-04-26 16:29
ok thanks, closing.

**Closed by sivann** 2016-04-26 16:29 UTC
